language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.0
    - 7.1
    - nightly
    - hhvm

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
        - php: hhvm

before_install:
    - composer self-update
    - pecl install -f mongodb
    - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
    - composer global require "fxp/composer-asset-plugin:^1.2.0"
    - composer install --prefer-dist

script:
    - composer test

after_script:
    - php ./vendor/bin/coveralls -v
